
import { MenuItem, Review, OperatingHours } from './types';

export const OPERATING_HOURS: OperatingHours = {
  Tuesday: { open: '17:00', close: '22:00' },
  Wednesday: { open: '17:00', close: '22:00' },
  Thursday: { open: '17:00', close: '22:00' },
  Friday: { open: '17:00', close: '22:00' },
  Saturday: { open: '16:00', close: '23:00' },
  Sunday: { open: '16:00', close: '23:00' },
};

export const SPECIALS_DATA: MenuItem[] = [
    {
        id: 101,
        name: 'Lobster & Potato Gratin',
        description: 'Decadent layers of potato, cream, and fresh lobster.',
        longDescription: 'A luxurious twist on a classic. Thinly sliced potatoes are layered with Gruyère cheese, heavy cream, and generous chunks of sweet, tender lobster meat. Baked until golden and bubbling, it\'s the ultimate indulgence.',
        price: 48,
        image: 'https://images.unsplash.com/photo-1628209804403-228359286f76?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        category: 'Main Courses',
        tags: [],
        ingredients: ['Potato', 'Lobster', 'Gruyère Cheese', 'Cream', 'Garlic'],
        isChefPick: true,
    },
    {
        id: 102,
        name: 'Purple Potato Mousse',
        description: 'A vibrant and surprisingly light dessert.',
        longDescription: 'Experience the unexpected. We transform purple potatoes into a silky, airy mousse, lightly sweetened and flavored with a hint of vanilla and lavender. Served with a crispy almond tuile, it\'s a dessert that will delight and surprise your palate.',
        price: 18,
        image: 'https://images.unsplash.com/photo-1590005023955-325f820a1a5b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        category: 'Desserts',
        tags: ['Vegetarian', 'Gluten-Free'],
        ingredients: ['Purple Potato', 'Coconut Cream', 'Vanilla', 'Lavender', 'Almond'],
    }
];

export const MENU_DATA: MenuItem[] = [
  // Appetizers
  {
    id: 1,
    name: 'Truffle Parmesan Potato Skins',
    description: 'Crispy potato skins, truffle oil, parmesan, chives.',
    longDescription: 'Our signature starter. We bake Russet potatoes to fluffy perfection, scoop them out, and fry the skins until golden brown. They are then tossed in aromatic truffle oil, generously dusted with aged Parmesan cheese, and sprinkled with fresh chives. Served with a side of garlic aioli.',
    price: 16,
    image: 'https://images.unsplash.com/photo-1585233898684-386b4d3228a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Appetizers',
    tags: ['Vegetarian'],
    ingredients: ['Potato', 'Truffle Oil', 'Parmesan Cheese', 'Chives', 'Garlic Aioli'],
    isPopular: true,
  },
  {
    id: 2,
    name: 'Spicy Potato Samosas',
    description: 'Indian-spiced potato filling, crispy pastry, mint chutney.',
    longDescription: 'A nod to Chef Pawan\'s heritage. These triangular pastries are filled with a tantalizing mixture of boiled potatoes, peas, and a secret blend of Indian spices. Fried to a perfect crisp, they offer a delightful crunch followed by a warm, spicy filling. Served with a cooling mint-coriander chutney.',
    price: 14,
    image: 'https://images.unsplash.com/photo-1631515243349-e0cb75582de3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Appetizers',
    tags: ['Vegan', 'Spicy'],
    ingredients: ['Potato', 'Peas', 'Flour', 'Spices', 'Mint', 'Coriander'],
  },
  {
    id: 3,
    name: 'Gourmet Poutine',
    description: 'Duck confit, cheese curds, gravy, hand-cut fries.',
    longDescription: 'Our elevated take on the Canadian classic. We start with our signature hand-cut potato fries, double-fried for extra crispiness. They are then topped with rich, savory duck confit, squeaky cheese curds, and smothered in a decadent house-made gravy.',
    price: 22,
    image: 'https://images.unsplash.com/photo-1582823695329-38b4a70a8232?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Appetizers',
    tags: [],
    ingredients: ['Potato', 'Duck Confit', 'Cheese Curds', 'Gravy'],
  },
  {
    id: 9,
    name: 'Peruvian Causa Rellena',
    description: 'Chilled potato terrine, avocado, chicken salad.',
    longDescription: 'A classic Peruvian dish. Layers of chilled, seasoned mashed potatoes are filled with a creamy chicken and avocado salad, and topped with a hard-boiled egg. A refreshing and flavorful starter.',
    price: 18,
    image: 'https://images.unsplash.com/photo-1632315352329-873539855524?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Appetizers',
    tags: ['Gluten-Free'],
    ingredients: ['Potato', 'Chicken', 'Avocado', 'Mayonnaise', 'Lime', 'Aji Amarillo'],
  },
  {
    id: 10,
    name: 'Loaded Sweet Potato Fries',
    description: 'Crispy sweet potato fries, black beans, jalapeños, cheese sauce.',
    longDescription: 'A mountain of our crispy sweet potato fries loaded with savory black beans, spicy pickled jalapeños, a creamy vegan cheese sauce, and a sprinkle of fresh cilantro. Perfect for sharing.',
    price: 17,
    image: 'https://images.unsplash.com/photo-1598827988286-6455a73e313d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Appetizers',
    tags: ['Vegan', 'Gluten-Free', 'Spicy'],
    ingredients: ['Sweet Potato', 'Black Beans', 'Jalapeños', 'Vegan Cheese', 'Cilantro'],
    isPopular: true,
  },
  
  // Main Courses
  {
    id: 4,
    name: 'Shepherd\'s Pie Reimagined',
    description: 'Slow-braised lamb, root vegetables, potato gratin topping.',
    longDescription: 'Comfort food, redefined. A rich stew of slow-braised lamb and hearty root vegetables is topped not with simple mash, but with a luxurious, creamy potato gratin dauphinois, baked until golden and bubbling. A true hug in a bowl.',
    price: 38,
    image: 'https://images.unsplash.com/photo-1621852004124-0313176b6630?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Main Courses',
    tags: [],
    ingredients: ['Lamb', 'Carrots', 'Onions', 'Potato', 'Cream', 'Cheese'],
    isChefPick: true,
  },
  {
    id: 5,
    name: 'Potato Gnocchi with Wild Mushroom Ragu',
    description: 'Hand-rolled potato gnocchi, earthy mushroom sauce, parmesan.',
    longDescription: 'Pillowy, light-as-air potato gnocchi, made fresh in-house daily. Tossed in a robust ragu of wild mushrooms, garlic, and herbs, and finished with a generous shaving of Parmigiano-Reggiano. A vegetarian masterpiece.',
    price: 32,
    image: 'https://images.unsplash.com/photo-1623961138859-aa29a738c232?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Main Courses',
    tags: ['Vegetarian'],
    ingredients: ['Potato', 'Flour', 'Egg', 'Wild Mushrooms', 'Garlic', 'Parmesan'],
    isPopular: true,
  },
  {
    id: 6,
    name: 'Crispy Skin Salmon with Potato Rosti',
    description: 'Pan-seared salmon, crispy potato rosti, dill cream sauce.',
    longDescription: 'A perfectly pan-seared salmon fillet with irresistibly crispy skin, served on a classic Swiss potato rosti. The dish is complemented by a light yet creamy dill sauce and a side of wilted spinach.',
    price: 40,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Main Courses',
    tags: ['Gluten-Free'],
    ingredients: ['Salmon', 'Potato', 'Dill', 'Cream', 'Spinach'],
  },
  {
    id: 11,
    name: 'Steak Frites Classique',
    description: '8oz flat iron steak, béarnaise sauce, hand-cut potato fries.',
    longDescription: 'The quintessential Parisian bistro dish. A perfectly cooked 8oz flat iron steak with a classic béarnaise sauce, served with a generous portion of our signature crispy, hand-cut potato fries. Simple, yet exquisitely satisfying.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1624329922245-a75d1532734a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Main Courses',
    tags: [],
    ingredients: ['Beef Steak', 'Potato', 'Egg Yolk', 'Butter', 'Tarragon'],
    isPopular: true,
  },
  {
    id: 12,
    name: 'Vegan Potato & Chickpea Curry',
    description: 'Aromatic coconut curry, potatoes, chickpeas, spinach, basmati rice.',
    longDescription: 'A hearty and comforting curry featuring tender potatoes and chickpeas simmered in a fragrant coconut milk-based sauce with spinach, ginger, garlic, and a blend of aromatic spices. Served with fluffy basmati rice.',
    price: 28,
    image: 'https://images.unsplash.com/photo-1588145152538-f6a8f15b3cce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Main Courses',
    tags: ['Vegan', 'Gluten-Free'],
    ingredients: ['Potato', 'Chickpeas', 'Coconut Milk', 'Spinach', 'Spices', 'Basmati Rice'],
  },
  
  // Desserts
  {
    id: 7,
    name: 'Sweet Potato Chocolate Brownie',
    description: 'Fudgy brownie made with sweet potato, vanilla ice cream.',
    longDescription: 'Our secret to the fudgiest brownie? Sweet potato puree! It creates an incredibly moist and dense texture. Made with dark chocolate and a hint of cinnamon, this gluten-free dessert is served warm with a scoop of vanilla bean ice cream.',
    price: 15,
    image: 'https://images.unsplash.com/photo-1593121553839-a78b3b1540a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Desserts',
    tags: ['Vegetarian', 'Gluten-Free'],
    ingredients: ['Sweet Potato', 'Dark Chocolate', 'Almond Flour', 'Vanilla Ice Cream'],
  },
  {
    id: 8,
    name: 'Potato & Cardamom Doughnuts',
    description: 'Warm, fluffy doughnuts, cinnamon sugar, caramel sauce.',
    longDescription: 'Mashed potato makes these doughnuts unbelievably light and fluffy. They are fried to order, tossed in a fragrant cardamom-cinnamon sugar, and served with a side of salted caramel dipping sauce. Pure indulgence.',
    price: 14,
    image: 'https://images.unsplash.com/photo-1627163434389-9d83296064a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Desserts',
    tags: ['Vegetarian'],
    ingredients: ['Potato', 'Flour', 'Cardamom', 'Cinnamon', 'Caramel'],
  },
  {
    id: 14,
    name: 'Potato Churros with Spiced Chocolate',
    description: 'Crispy on the outside, fluffy inside. Served with dipping sauce.',
    longDescription: 'A delightful twist on a classic. Potato in the dough makes these churros incredibly light and fluffy. Fried to golden perfection, dusted with cinnamon sugar, and served with a warm, spiced dark chocolate dipping sauce.',
    price: 15,
    image: 'https://images.unsplash.com/photo-1552339227-242862a9a7a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Desserts',
    tags: ['Vegetarian'],
    ingredients: ['Potato', 'Flour', 'Cinnamon', 'Dark Chocolate', 'Chili Powder'],
  },

  // Beverages
  {
    id: 15,
    name: 'Potato Vodka Martini',
    description: 'Ultra-smooth potato vodka, dry vermouth, choice of olive or twist.',
    longDescription: 'Experience the clean, crisp taste of a premium potato vodka in this classic cocktail. Shaken or stirred to your preference with a whisper of dry vermouth and garnished with either olives or a lemon twist.',
    price: 18,
    image: 'https://images.unsplash.com/photo-1623593688624-99836e594191?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Beverages',
    tags: [],
    ingredients: ['Potato Vodka', 'Dry Vermouth', 'Olive', 'Lemon']
  },
  {
    id: 16,
    name: 'Rosemary Grapefruit Fizz',
    description: 'A refreshing non-alcoholic spritz with herbal and citrus notes.',
    longDescription: 'A sophisticated mocktail featuring fresh grapefruit juice, a house-made rosemary simple syrup, and topped with sparkling water. A perfectly balanced and refreshing drink for any time of day.',
    price: 12,
    image: 'https://images.unsplash.com/photo-1625862362532-a58f4b0051e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Beverages',
    tags: ['Vegan'],
    ingredients: ['Grapefruit Juice', 'Rosemary', 'Sparkling Water']
  },
  {
    id: 17,
    name: '"The Spud" Old Fashioned',
    description: 'Sweet potato-infused bourbon, bitters, orange peel.',
    longDescription: 'Our unique take on a timeless classic. We infuse bourbon with roasted sweet potato and cinnamon, then stir it with aromatic bitters and a touch of sugar. Served over a large ice cube with an orange peel garnish.',
    price: 20,
    image: 'https://images.unsplash.com/photo-1586971576182-4161a09424c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Beverages',
    tags: [],
    ingredients: ['Bourbon', 'Sweet Potato', 'Bitters', 'Orange Peel'],
    isChefPick: true,
  },
  {
    id: 18,
    name: 'Artisanal Coffee',
    description: 'Locally roasted single-origin beans, prepared as pour-over or espresso.',
    longDescription: 'We partner with a local roaster to bring you exceptional single-origin coffee. Choose your preparation: a meticulous pour-over to highlight delicate notes, or a classic espresso for a rich, intense flavor.',
    price: 6,
    image: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Beverages',
    tags: ['Vegan'],
    ingredients: ['Coffee Beans', 'Water'],
  },
  {
    id: 19,
    name: 'Local Craft Beer',
    description: 'A rotating selection of the best IPAs and Lagers from local breweries.',
    longDescription: 'We proudly support our local craft beer scene. Ask your server about our current rotating taps, featuring a curated selection of IPAs, Lagers, Stouts, and Sours from the best breweries in the area.',
    price: 9,
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Beverages',
    tags: [],
    ingredients: ['Hops', 'Barley', 'Yeast', 'Water'],
  },
  {
    id: 20,
    name: 'House Red & White Wine',
    description: 'Curated selections of red and white wine, available by the glass or bottle.',
    longDescription: 'Our sommelier has carefully selected versatile and food-friendly red and white wines to complement our menu. Currently featuring a fruit-forward Pinot Noir and a crisp Sauvignon Blanc. Available by the glass or bottle.',
    price: 14,
    image: 'https://images.unsplash.com/photo-1594236391442-990a41d6f461?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: 'Beverages',
    tags: [],
    ingredients: ['Grapes'],
  },
];


export const REVIEWS_DATA: Review[] = [
  {
    author: 'Sarah L.',
    rating: 5,
    text: 'Absolutely blown away by the creativity! The Potato Gnocchi was like eating a cloud. I never knew potatoes could be so elegant. The ambiance is cozy and the service was impeccable. A new favorite!',
    avatar: 'https://i.pravatar.cc/150?img=1'
  },
  {
    author: 'David C.',
    rating: 5,
    text: 'The Gourmet Poutine is a game-changer. Rich duck confit and perfect fries. My wife had the salmon and said it was the best she\'s ever had. We\'ll be back to try the rest of the menu.',
    avatar: 'https://i.pravatar.cc/150?img=2'
  },
  {
    author: 'Mei F.',
    rating: 4,
    text: 'A very enjoyable dinner. The Spicy Samosas had a great kick and the brownie was surprisingly delicious (couldn\'t even tell it had sweet potato!). It was a bit noisy, but the food made up for it.',
    avatar: 'https://i.pravatar.cc/150?img=3'
  }
];

export const GALLERY_IMAGES = [
  'https://images.unsplash.com/photo-1551024709-8f237c2045e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&h=800&q=80',
  'https://images.unsplash.com/photo-1541542159-81812519a27d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&h=600&q=80',
  'https://images.unsplash.com/photo-1515003197210-90cd718e0f9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&h=800&q=80',
  'https://images.unsplash.com/photo-1505253716362-afb749868512?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&h=600&q=80',
  'https://images.unsplash.com/photo-1574783756580-5d0e2e783ead?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&h=600&q=80',
  'https://images.unsplash.com/photo-1592861956120-e524fc739696?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&h=800&q=80',
  'https://images.unsplash.com/photo-1617093727264-3918b2c4e323?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&h=600&q=80',
  'https://images.unsplash.com/photo-1621239413233-a82869588145?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&h=800&q=80',
];
